// DERMATOME
export const SET_DERMATOME = 'SET_DERMATOME'
export const RETRIEVE_DERMATOME = 'RETRIEVE_DERMATOME'
// DERMATOME2
export const SET_DERMATOME2 = 'SET_DERMATOME2'
export const RETRIEVE_DERMATOME2 = 'RETRIEVE_DERMATOME2'
